In [1]:
import tensorflow as tf

## Tensor
- Row vector X contain 12 integers starting from 0.
- Tensor with 1 axis = Vector, Tensor with 2 axis = Matrix
- Tensor with axis more than 2 have no specific name in Mathematic

In [3]:
x = tf.range(12)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

```Shape``` = length along axis <br/>
```Size``` = total number of elements in a tensor

In [4]:
x.shape

TensorShape([12])

In [5]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

- Transform from vector (12,) to matrix shape (3, 4)
- (12,) means vector with 12 elements
- (3, 4) means 3 rows and 4 columns
- (2, 3, 4) means 2 elements of matrix 3 rows 4 columns

In [7]:
X = tf.reshape(x, (3, 4))
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [8]:
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [19]:
tf.ones((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

Random number from normal distributin with (3, 4) shape

In [20]:
tf.random.normal(shape = [3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.80631095, -1.0628055 , -0.73113376, -0.01850129],
       [-0.24056083,  0.6278568 ,  0.9746796 , -0.26133102],
       [-0.46019053, -0.11292906, -0.60763943,  0.5989874 ]],
      dtype=float32)>

In [22]:
tf.constant([[1, 2, 3 , 4], [1, 2, 3, 4], [1, 2, 3, 4]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]], dtype=int32)>

## Operations

### Elementwise - Scala
Tensor with identical shape

In [23]:
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])

In [25]:
x + y, x - y

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>)

In [27]:
x * y, x/ y

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>)

In [28]:
x**y

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>

In [29]:
tf.exp(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
      dtype=float32)>

### Concatenate

In [30]:
X = tf.reshape(tf.range(12, dtype =tf.float32), (3,4))
Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

axis = 0, along rows

In [31]:
tf.concat([X, Y], axis = 0)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 2.,  1.,  4.,  3.],
       [ 1.,  2.,  3.,  4.],
       [ 4.,  3.,  2.,  1.]], dtype=float32)>

axis = 1, along columns

In [32]:
tf.concat([X, Y], axis = 1)

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
       [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
       [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>

Sum all elements in tensor

In [33]:
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

### Broadcasting Mechanism

In [34]:
a = tf.reshape(tf.range(3), (3, 1))
b = tf.reshape(tf.range(2), (1, 2))
a, b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

In [35]:
a + b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

### Indexing and Slicing

In [37]:
X

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [39]:
X[-1]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>

In [45]:
X[1:3]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

### Assigning
Tensors in Tensorflow are immutable, and cannot be assigned to. <br/>
Variables in Tensorflow are mutable containers of state that support assignments.

In [46]:
X_var = tf.Variable(X)

In [48]:
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [49]:
X_var[1, 2].assign(9)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [60]:
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  9.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [63]:
X_var[0:2, :]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 1., 2., 3.],
       [4., 5., 9., 7.]], dtype=float32)>

In [65]:
tf.ones(X_var[0:2,:].shape, dtype = tf.float32) * 12

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [12., 12., 12., 12.]], dtype=float32)>

In [64]:
X_var = tf.Variable(X)
X_var[0:2, :].assign(tf.ones(X_var[0:2,:].shape, dtype = tf.float32) * 12)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

### Saving Memory

In [71]:
Y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]], dtype=float32)>

In [75]:
Z = tf.Variable(tf.zeros_like(Y))

print('id(Z):', id(Z))
Z.assign(X + Y)

print('id(Z):', id(Z))

id(Z): 140605435790960
id(Z): 140605435790960


### Conversion to Other Python Objects

In [77]:
A = X.numpy()
B = tf.constant(A)

type(A), type(B)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)

In [78]:
a = tf.constant ([3.5]).numpy()
a, a.item(), float(a), int(a)

(array([3.5], dtype=float32), 3.5, 3.5, 3)