### Concise Implementation Linear Regression
Using high-level API from Tenforflow

In [1]:
%matplotlib inline
import math
import time
import numpy as np
import tensorflow as tf
import random

from d2l import tensorflow as d2l

In [2]:
true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [4]:
def load_array(data_arrays, batch_size, is_train = True): #@save
    """Create Tensorflow data iterator"""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size= 1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [9]:
for X, y in data_iter:
    print(X, '\n', y)
    break

tf.Tensor(
[[ 1.0003303   1.329978  ]
 [-0.90214384  0.10723342]
 [ 1.6717176  -0.12233017]
 [ 0.09739774  0.81526715]
 [ 0.4542425   0.28731757]
 [ 0.09204767 -0.28580478]
 [ 0.06367436  0.22503243]
 [ 0.12841602  1.5715094 ]
 [ 1.0931038   0.52389044]
 [-0.6931267  -0.5613458 ]], shape=(10, 2), dtype=float32) 
 tf.Tensor(
[[ 1.6782206 ]
 [ 2.0144842 ]
 [ 7.9592214 ]
 [ 1.6272616 ]
 [ 4.1282544 ]
 [ 5.3577657 ]
 [ 3.5628486 ]
 [-0.88763005]
 [ 4.5985985 ]
 [ 4.713464  ]], shape=(10, 1), dtype=float32)


### Define Model

In [7]:
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

### Initializing Model Parameters

In [ ]:
initializer = tf.initializers.RandomNormal(stddev = 0.01)

net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

### Define Loss Function

In [12]:
loss = tf.keras.losses.MeanSquaredError()

### Define Optimization Algorithm

In [13]:
trainer = tf.keras.optimizers.SGD(learning_rate = 0.03)

### Training

In [14]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training = True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000156
epoch 2, loss 0.000096
epoch 3, loss 0.000096


In [15]:
net.trainable_variables

[<tf.Variable 'dense/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[ 2.0002081],
        [-3.3994668]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([4.199846], dtype=float32)>]

In [16]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([-0.00020814 -0.00053334], shape=(2,), dtype=float32)
error in estimating b [0.00015402]
